spring.application.name=api-gateway
server.port=1111

# ---------------- EUREKA ----------------
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# =========================================================
# ROUTES
# =========================================================

# -------- USER SERVICE (Auth / Users) --------
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**,/api/auth/**

# -------- TRIP SERVICE --------
spring.cloud.gateway.routes[1].id=trip-service
spring.cloud.gateway.routes[1].uri=lb://TRIP-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/trips/**

# -------- LOCATION SERVICE --------
spring.cloud.gateway.routes[2].id=location-service
spring.cloud.gateway.routes[2].uri=lb://LOCATION-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/location/**

# -------- PAYMENT SERVICE --------
spring.cloud.gateway.routes[3].id=payment-service
spring.cloud.gateway.routes[3].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/payments/**

# -------- RATING SERVICE --------
spring.cloud.gateway.routes[4].id=rating-service
spring.cloud.gateway.routes[4].uri=lb://RATING-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/ratings/**