spring.application.name=rating-service
server.port=8010
# ---------------- DB CONFIG ----------------
spring.datasource.url=jdbc:postgresql://localhost:5432/rating_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ---------------- JPA CONFIG ----------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
